apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: nexus
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: kubemaster
    path: "/mnt/nfs/k8s/nexus"
    readOnly: false