apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sonar
  labels:
    #app: keycloak
    environment: dev
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"                   #Dont use this on prod
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "sonar,postgres"   #Dont use this on prod
type: Opaque
data:
  #KEYCLOAK_USER: YWRtaW4=  
  #KEYCLOAK_PASSWORD: VzNsY29tRTEyMyMj               
  #KEYCLOAK_FRONTEND_URL: aHR0cHM6Ly9rZXljbG9hay5zcy1zaWViZWwuY29tL2F1dGgv
  #KEYCLOAK_ADMIN_URL: aHR0cHM6Ly9rZXljbG9hay5zcy1zaWViZWwuY29tL2F1dGgvcmVhbG1zL21hc3Rlci9hZG1pbi8=                
  DB_VENDOR: UE9TVEdSRVM=
  DB_ADDR: cG9zdGdyZXMtc2VydmljZS5wb3N0Z3Jlcy5zdmMuY2x1c3Rlci5sb2NhbA==
  DB_PORT: NTQzMg==
  DB_DATABASE: a29uZw==
  DB_USER: a29uZw==
  DB_PASSWORD: a29uZw==