apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv
  namespace: sonar
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: kube-master
    path: "/mnt/nfs/k8s/sonar"
    readOnly: false