apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: postgres
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: kubemaster
    path: "/mnt/nfs/k8s/postgresql"
    readOnly: false