#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: postgresql
#  namespace: postgres
#  labels:
#    app: postgresql
#data:
#  POSTGRESQL_USERNAME: sonar_user
#  POSTGRESQL_DATABASE: sonar_db
#  POSTGRESQL_PASSWORD: S0N4RQUB3
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres
  labels:
    app: postgresql
spec:
  ports:
  - port: 5432
    name: postgresql
  selector:
    app: postgresql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: postgres
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      securityContext:
        #runAsUser: 2000
        #runAsGroup: 2000
        fsGroup: 1000 
      containers:
      - name: postgress
        image: bitnami/postgresql:14
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_DATABASE
        volumeMounts:
        - name: postgresql
          mountPath: /bitnami/postgresql
      volumes:
      - name: postgresql
        persistentVolumeClaim:
          claimName: postgresql-pvc
---